server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.27.127:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 6f5e350fb8
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.217.136
  rabbitmq:
    host: 192.168.217.136
jwt:
  config:
    key: itcast
    ttl: 3600000