server: 
  port: 9009
spring: 
  application:  
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.1.100
aliyun:
  sms:
    AccessKeyID: LTAIOq0JN7Cbmmiu
    accessKeySecret: XjlmLpvKBtKybMKT3mozT5oGrbPFYM
    template_code: SMS_123456
    sign_name: EVELIA
