server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.190.27.127:3306/tensquare_qa?characterEncoding=UTF8
    username: root
    password: 6f5e350fb8
  jpa: 
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast